# pin llvm<16 because of: https://bugreports.qt.io/browse/PYSIDE-2288
c_compiler_version:        # [osx]
  - 15                     # [osx]
cxx_compiler_version:      # [osx]
  - 15                     # [osx]

c_stdlib_version:   # [linux]
  - "2.17"          # [linux]
