{% set version = "5.9.0a1" %}

package:
  name: pyside2
  version: {{ version }}

source:
  git_url: https://codereview.qt-project.org/pyside/pyside-setup
  git_tag: 5.9
  patches:
    # https://bugreports.qt.io/browse/PYSIDE-140
    - 0001-Release-Py_buffer-after-gets-its-underlying-pointer.patch
    # https://codereview.qt-project.org/c/pyside/pyside-setup/+/263267
    - 55d8970.patch
    # https://codereview.qt-project.org/c/pyside/pyside-setup/+/262953
    - project.patch
    # https://codereview.qt-project.org/c/pyside/pyside-setup/+/263251
    - 0001-shiboken-Provide-g-internal-headers-for-CentOS-too.patch
    # https://bugreports.qt.io/browse/PYSIDE-1012
    - gnu_includes.patch

build:
  number: 0
  skip: true  # [win and vc<14]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
  host:
    - clangdev
    - llvmdev
    - python
    - qt
    - libxslt
    - libxml2
  run:
    - clangdev
    - llvmdev
    - python
    - qt
    - libxslt
    - libxml2

test:
  imports:
    - PySide2.QtCharts
    - PySide2.QtConcurrent
    - PySide2.QtCore
    - PySide2.QtDataVisualization
    - PySide2.QtGui
    - PySide2.QtHelp
    - PySide2.QtLocation
    - PySide2.QtMultimedia
    - PySide2.QtMultimediaWidgets
    - PySide2.QtNetwork
    - PySide2.QtOpenGL
    - PySide2.QtPositioning
    - PySide2.QtPrintSupport
    - PySide2.QtQml
    - PySide2.QtQuick
    - PySide2.QtQuickWidgets
    - PySide2.QtScript
    - PySide2.QtScriptTools
    - PySide2.QtScxml
    - PySide2.QtSensors
    - PySide2.QtSql
    - PySide2.QtSvg
    - PySide2.QtTest
    - PySide2.QtTextToSpeech
    - PySide2.QtUiTools
    - PySide2.QtWebChannel
    - PySide2.QtWebEngineCore
    - PySide2.QtWebEngineWidgets
    - PySide2.QtWebSockets
    - PySide2.QtWidgets
    - PySide2.QtXml
    - PySide2.QtXmlPatterns
    - PySide2.Qt3DAnimation
    - PySide2.Qt3DCore
    - PySide2.Qt3DExtras
    - PySide2.Qt3DInput
    - PySide2.Qt3DLogic
    - PySide2.Qt3DRender

  commands:
    - shiboken2 --help
    - pyside2-lupdate -help
    - pyside2-rcc -help
    - pyside2-uic -help

about:
  home: https://wiki.qt.io/PySide2
  license: LGPL3
  license_file: LICENSE.LGPL3
  summary: Python bindings for Qt

extra:
  recipe-maintainers:
    - jschueller
