{% set version = "6.4.2" %}

package:
  name: pyside6
  version: {{ version }}

source:
  url: https://download.qt.io/official_releases/QtForPython/pyside6/PySide6-{{ version }}-src/pyside-setup-opensource-src-{{ version }}.tar.xz
  sha256: 1ec9d0936332efd229650cf10fed36cadddff7a613a2ea6e897de4d504c1b505
  patches:
    # https://bugreports.qt.io/browse/PYSIDE-1193
    - patches/pyi_osx.patch

    # https://bugreports.qt.io/browse/PYSIDE-2057
    - patches/do_not_store_build_time_compiler.patch

    # https://bugreports.qt.io/browse/PYSIDE-2090
    - patches/build_generator.patch

    # https://bugreports.qt.io/browse/PYSIDE-2183
    - patches/support.patch

    # https://bugreports.qt.io/browse/PYSIDE-2184
    - patches/install_pyi.patch

build:
  number: 0
  ignore_run_exports:
    # make it optional
    - qt6-3d
    - qt6-charts
    - qt6-datavis3d

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libclang                           # [build_platform != target_platform]
    - llvmdev                            # [build_platform != target_platform]
    - clangdev                           # [build_platform != target_platform]
    - python                             # [build_platform != target_platform]
    #- cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - libxslt                            # [build_platform != target_platform]
    - libxml2                            # [build_platform != target_platform]
    - qt6-main                           # [build_platform != target_platform]
    - sysroot_linux-64 2.17              # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl') }}           # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('libsm-devel') }}           # [linux]
    - {{ cdt('libice-devel') }}          # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxcb-devel') }}          # [linux]
    - {{ cdt('expat-devel') }}           # [linux]
    - {{ cdt('pcre') }}                  # [linux]
    - {{ cdt('libglvnd-glx') }}          # [linux]
    - {{ cdt('libglvnd-egl') }}          # [linux]
    - {{ cdt('libxkbcommon-devel') }}    # [linux]
    - {{ cdt('xcb-util-devel') }}        # [linux]
    - {{ cdt('xcb-util-image-devel') }}  # [linux]
    - {{ cdt('xcb-util-keysyms-devel') }}     # [linux]
    - {{ cdt('xcb-util-renderutil-devel') }}  # [linux]
    - {{ cdt('xcb-util-wm-devel') }}          # [linux]

  host:
    - python
    - libxslt
    - libxml2
    - qt6-main
    - qt6-3d
    - qt6-charts
    - qt6-datavis3d
    - llvmdev
    # for libclang
    - clangdev
    - libclang
    - llvmdev  {{ cxx_compiler_version }}  # [osx]
    - clangdev {{ cxx_compiler_version }}  # [osx]
  run:
    - python
    - {{ pin_compatible("libclang") }}

test:
  requires:
    # these are optional
    # test them with one version of python
    - qt6-3d               # [py==310]
    - qt6-charts           # [py==310]
    - qt6-datavis3d        # [py==310]

    - sysroot_linux-64 2.17              # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl') }}           # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('libsm-devel') }}           # [linux]
    - {{ cdt('libice-devel') }}          # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxcb-devel') }}          # [linux]
    - {{ cdt('expat-devel') }}           # [linux]
    - {{ cdt('pcre') }}                  # [linux]
    - {{ cdt('libglvnd-glx') }}          # [linux]
    - {{ cdt('libglvnd-egl') }}          # [linux]
    - {{ cdt('libxkbcommon-devel') }}    # [linux]
    - {{ cdt('xcb-util-devel') }}        # [linux]
    - {{ cdt('xcb-util-image-devel') }}  # [linux]
    - {{ cdt('xcb-util-keysyms-devel') }}     # [linux]
    - {{ cdt('xcb-util-renderutil-devel') }}  # [linux]
    - {{ cdt('xcb-util-wm-devel') }}          # [linux]
  imports:
    - PySide6.Qt3DAnimation        # [py==310]
    - PySide6.Qt3DCore             # [py==310]
    - PySide6.Qt3DExtras           # [py==310]
    - PySide6.Qt3DInput            # [py==310]
    - PySide6.Qt3DLogic            # [py==310]
    - PySide6.Qt3DRender           # [py==310]
    #- PySide6.QtBluetooth
    - PySide6.QtCharts             # [py==310]
    - PySide6.QtConcurrent
    - PySide6.QtCore
    - PySide6.QtDataVisualization  # [py==310]
    #- PySide6.QtDesigner
    - PySide6.QtGui
    - PySide6.QtHelp
    #- PySide6.QtHttpServer
    - PySide6.QtMultimedia
    - PySide6.QtMultimediaWidgets
    - PySide6.QtNetwork
    #- PySide6.QtNetworkAuth
    #- PySide6.QtNfc
    - PySide6.QtOpenGL
    - PySide6.QtOpenGLWidgets
    #- PySide6.QtPdf
    #- PySide6.QtPdfWidgets
    - PySide6.QtPositioning
    - PySide6.QtPrintSupport
    - PySide6.QtQml
    - PySide6.QtQuick
    #- PySide6.QtQuick3D
    - PySide6.QtQuickControls2
    - PySide6.QtQuickWidgets
    #- PySide6.QtRemoteObjects
    - PySide6.QtScxml
    - PySide6.QtSensors
    - PySide6.QtSerialPort
    - PySide6.QtSpatialAudio
    - PySide6.QtSql
    - PySide6.QtStateMachine
    - PySide6.QtSvg
    - PySide6.QtSvgWidgets
    - PySide6.QtTest
    #- PySide6.QtTextToSpeech
    - PySide6.QtUiTools
    - PySide6.QtWebChannel
    #- PySide6.QtWebEngineCore
    #- PySide6.QtWebEngineQuick
    #- PySide6.QtWebEngineWidgets
    - PySide6.QtWebSockets
    - PySide6.QtWidgets
    - PySide6.QtXml
  commands:
    - shiboken6 --help

about:
  home: https://wiki.qt.io/PySide2
  license: LGPL-3.0-only
  license_file: LICENSES/LGPL-3.0-only.txt
  summary: Python bindings for Qt

extra:
  recipe-maintainers:
    - jan-janssen
    - jschueller
