{% set version = "5.15.4" %}

package:
  name: pyside2
  version: {{ version }}

source:
  url: https://download.qt.io/official_releases/QtForPython/pyside2/PySide2-{{ version }}-src/pyside-setup-opensource-src-{{ version }}.tar.xz
  sha256: 3c68ed0def4111ef5d0641370306338d277ae8983a77eaf22f223ddd3a14450b
  patches:
    # https://bugreports.qt.io/browse/PYSIDE-1193
    - patches/pyi.patch
    - patches/python3.10.patch
    - patches/windows_dll_shiboken_fix.patch
    - patches/fix_genererate_pyi.patch  # [win]
    - patches/pyside2-tools-obsolete.patch

build:
  number: 1
  detect_binary_files_with_prefix: true
  entry_points:
    - pyside2-designer = PySide2.scripts.pyside_tool:designer
    - pyside2-rcc = PySide2.scripts.pyside_tool:rcc
    - pyside2-uic = PySide2.scripts.pyside_tool:uic

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clangdev
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxrandr') }}             # [linux]
    - {{ cdt('alsa-lib') }}              # [linux]
    - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]
    - make                               # [not win]
    - ninja                              # [win]
    - gxx                                # [linux]

  host:
    - python
    - packaging
    - qt-main
    - qt-webengine
    - libxml2
    - libxslt
    - pip
    - setuptools
    - libclang
  run:
    - python

test:
  imports:
    - PySide2.QtCharts
    - PySide2.QtConcurrent
    - PySide2.QtCore
    - PySide2.QtDataVisualization
    - PySide2.QtGui
    - PySide2.QtHelp
    - PySide2.QtLocation
    - PySide2.QtMultimedia
    - PySide2.QtMultimediaWidgets
    - PySide2.QtNetwork
    - PySide2.QtOpenGL
    - PySide2.QtPositioning
    - PySide2.QtPrintSupport
    - PySide2.QtQml
    - PySide2.QtQuick
    - PySide2.QtQuickWidgets
    - PySide2.QtRemoteObjects
    - PySide2.QtScript
    - PySide2.QtScriptTools
    - PySide2.QtScxml
    - PySide2.QtSensors
    - PySide2.QtSql
    - PySide2.QtSvg
    - PySide2.QtTest
    - PySide2.QtTextToSpeech
    - PySide2.QtUiTools
    - PySide2.QtWebChannel
    - PySide2.QtWebEngineCore
    - PySide2.QtWebEngineWidgets
    - PySide2.QtWebSockets
    - PySide2.QtWidgets
    - PySide2.QtXml
    - PySide2.QtXmlPatterns
    - PySide2.Qt3DAnimation
    - PySide2.Qt3DCore
    - PySide2.Qt3DExtras
    - PySide2.Qt3DInput
    - PySide2.Qt3DLogic
    - PySide2.Qt3DRender

  commands:
    - shiboken2 --help
    - pyside2-lupdate -help
    - pyside2-rcc -help
    - pyside2-uic -help
    # Ensure installs are registered properly with pip
    - pip show PySide2
    - pip show shiboken2

  requires:
    - pip

about:
  home: https://wiki.qt.io/PySide2
  license:  LGPL-3.0-only
  license_file: LICENSE.LGPLv3
  summary: Python bindings for Qt

extra:
  recipe-maintainers:
    - jan-janssen
    - jschueller
