{% set version = "5.13.2" %}

package:
  name: pyside2
  version: {{ version }}

source:
  fn: pyside-setup-everywhere-src-{{ version }}.tar.xz
  url: https://download.qt.io/official_releases/QtForPython/pyside2/PySide2-{{ version }}-src/pyside-setup-opensource-src-{{ version }}.tar.xz
  sha256: 3e255d64df08880d0281ebe86009d5ea45f24332b308954d967c33995f75e543
  patches:
    # https://codereview.qt-project.org/c/pyside/pyside-tools/+/270008
    - 0001-Make-pyside2-uic-executable-by-windows-shell.patch
    # https://bugreports.qt.io/browse/PYSIDE-1193
    - pyi.patch
    # pyside2 5.13.1 needs a few backports from 5.14 to work with python3.8
    - 0002-Fix-Python-3.8-problems.patch
    - 0003-Optimize-the-Python-3.8-refcount-fix-a-tiny-bit.patch
    - 0004-make-compilation-work-after-backporting.patch

build:
  number: 2
  skip: true  # [win and vc<14]
  detect_binary_files_with_prefix: True

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clangdev
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxrandr') }}             # [linux]
    - {{ cdt('alsa-lib') }}              # [linux]
    - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]

  host:
    - python
    - qt
    - libxml2
    - libxslt
  run:
    - python

test:
  imports:
    - PySide2.QtCharts
    - PySide2.QtConcurrent
    - PySide2.QtCore
    - PySide2.QtDataVisualization
    - PySide2.QtGui
    - PySide2.QtHelp
    - PySide2.QtLocation
    - PySide2.QtMultimedia
    - PySide2.QtMultimediaWidgets
    - PySide2.QtNetwork
    - PySide2.QtOpenGL
    - PySide2.QtPositioning
    - PySide2.QtPrintSupport
    - PySide2.QtQml
    - PySide2.QtQuick
    - PySide2.QtQuickWidgets
    - PySide2.QtRemoteObjects
    - PySide2.QtScript
    - PySide2.QtScriptTools
    - PySide2.QtScxml
    - PySide2.QtSensors
    - PySide2.QtSql
    - PySide2.QtSvg
    - PySide2.QtTest
    - PySide2.QtTextToSpeech
    - PySide2.QtUiTools
    - PySide2.QtWebChannel
    - PySide2.QtWebEngineCore
    - PySide2.QtWebEngineWidgets
    - PySide2.QtWebSockets
    - PySide2.QtWidgets
    - PySide2.QtXml
    - PySide2.QtXmlPatterns
    - PySide2.Qt3DAnimation
    - PySide2.Qt3DCore
    - PySide2.Qt3DExtras
    - PySide2.Qt3DInput
    - PySide2.Qt3DLogic
    - PySide2.Qt3DRender

  commands:
    - shiboken2 --help
    - pyside2-lupdate -help
    - pyside2-rcc -help
    - pyside2-uic -help

about:
  home: https://wiki.qt.io/PySide2
  license: LGPL3
  license_file: LICENSE.LGPLv3
  summary: Python bindings for Qt

extra:
  recipe-maintainers:
    - jschueller
