{% set version = "5.15.15" %}

package:
  name: pyside2
  version: {{ version }}

source:
  url: https://download.qt.io/official_releases/QtForPython/pyside2/PySide2-{{ version }}-src/pyside-setup-opensource-src-{{ version }}.tar.xz
  sha256: 21d6818b064834b08501180e48890e5fd87df2fb3769f80c58143457f548c408
  patches:
    - patches/python3.12.patch  # [py == 312]
    # https://bugreports.qt.io/browse/PYSIDE-1193
    - patches/pyi.patch
    - patches/windows_dll_shiboken_fix.patch
    - patches/fix_genererate_pyi.patch  # [win]
    - patches/pyside2-tools-obsolete.patch
    - patches/cross_compile_pyi.patch  # [build_platform != target_platform]
    # https://github.com/conda-forge/pyside2-feedstock/issues/130
    # https://bugreports.qt.io/browse/PYSIDE-2057
    - patches/do_not_store_build_time_compiler.patch
    # https://bugreports.qt.io/browse/PYSIDE-2183
    - patches/support.patch

    # https://bugreports.qt.io/browse/PYSIDE-2184
    - patches/install_pyi.patch

    # https://bugreports.qt.io/browse/PYSIDE-2187
    - patches/gluint.patch

build:
  number: 1
  detect_binary_files_with_prefix: true
  entry_points:
    - pyside2-designer = PySide2.scripts.pyside_tool:designer
    - pyside2-rcc = PySide2.scripts.pyside_tool:rcc
    - pyside2-uic = PySide2.scripts.pyside_tool:uic
  ignore_run_exports:
    # make it optional. Use the constraints on qt-main
    # and qt to ensure that qt-webengine is correctly installed
    - qt-webengine

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pyside2  {{ version }}                 # [build_platform != target_platform]
    - qt-main  {{ version }}                 # [build_platform != target_platform]
    - qt-webengine  {{ version }}            # [build_platform != target_platform]
    - cmake <4
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - clangdev >=9
  host:
    - libgl-devel                        # [linux]
    - libegl-devel                       # [linux]
    - libopengl-devel                    # [linux]
    - libdrm                             # [linux]
    - python
    - packaging
    - qt-main       {{ version }}
    - qt-webengine  {{ version }}
    - libxml2 >=2.14.7
    - libxslt
    - pip
    - setuptools
    - clangdev >=9
    - libclang
    - llvmdev  {{ cxx_compiler_version }}  # [osx]
    - clangdev {{ cxx_compiler_version }}  # [osx]
    - xcb-util                           # [linux]
    - xcb-util-wm                        # [linux]
    - xcb-util-keysyms                   # [linux]
    - xcb-util-image                     # [linux]
    - xcb-util-renderutil                # [linux]
    - xorg-libx11                        # [linux]
    - xorg-libxcb                        # [linux]
    - xorg-libxext                       # [linux]
    - xorg-libxdamage                    # [linux]
    - xorg-libsm                         # [linux]
    - xorg-libice                        # [linux]
    - xorg-libxcomposite                 # [linux]
    - xorg-libxxf86vm                    # [linux]
    - xorg-xf86vidmodeproto              # [linux]
  run:
    - python

test:
  imports:
    - PySide2.QtCharts
    - PySide2.QtConcurrent
    - PySide2.QtCore
    - PySide2.QtDataVisualization
    - PySide2.QtGui
    - PySide2.QtHelp
    - PySide2.QtLocation
    - PySide2.QtMultimedia
    - PySide2.QtMultimediaWidgets
    - PySide2.QtNetwork
    - PySide2.QtOpenGL
    - PySide2.QtPositioning
    - PySide2.QtPrintSupport
    - PySide2.QtQml
    - PySide2.QtQuick
    - PySide2.QtQuickWidgets
    - PySide2.QtRemoteObjects
    - PySide2.QtScript
    - PySide2.QtScriptTools
    - PySide2.QtScxml
    - PySide2.QtSensors
    - PySide2.QtSql
    - PySide2.QtSvg
    - PySide2.QtTest
    - PySide2.QtTextToSpeech
    - PySide2.QtUiTools
    - PySide2.QtWebChannel
    - PySide2.QtWebEngineCore     # [py==310]
    - PySide2.QtWebEngineWidgets  # [py==310]
    - PySide2.QtWebSockets
    - PySide2.QtWidgets
    - PySide2.QtXml
    - PySide2.QtXmlPatterns
    - PySide2.Qt3DAnimation
    - PySide2.Qt3DCore
    - PySide2.Qt3DExtras
    - PySide2.Qt3DInput
    - PySide2.Qt3DLogic
    - PySide2.Qt3DRender

  commands:
    - shiboken2 --help
    - pyside2-lupdate -help
    - pyside2-rcc -help
    - pyside2-uic -help
    # Ensure installs are registered properly with pip
    - pip show PySide2
    - pip show shiboken2

  requires:
    - pip
    - qt-webengine   # [py==310]

about:
  home: https://wiki.qt.io/PySide2
  license: LGPL-3.0-only
  license_file: LICENSE.LGPLv3
  summary: Python bindings for Qt

extra:
  recipe-maintainers:
    - jan-janssen
    - jschueller
    - hmaarrfk
