{% set version = "5.15.8" %}

package:
  name: pyside2
  version: {{ version }}

source:
  url: https://download.qt.io/official_releases/QtForPython/pyside2/PySide2-{{ version }}-src/pyside-setup-opensource-src-{{ version }}.tar.xz
  sha256: 23436302c8deb5b4cbc769b205d09604e38ba83b40708efccb7bd8c9af6f6b5d
  patches:
    # https://bugreports.qt.io/browse/PYSIDE-1193
    - patches/pyi.patch
    - patches/python3.10.patch
    - patches/windows_dll_shiboken_fix.patch
    - patches/fix_genererate_pyi.patch  # [win]
    - patches/pyside2-tools-obsolete.patch
    - patches/cross_compile_pyi.patch  # [build_platform != target_platform]
    # https://github.com/conda-forge/pyside2-feedstock/issues/130
    # https://bugreports.qt.io/browse/PYSIDE-2057
    - patches/do_not_store_build_time_compiler.patch
    # Supports Python 3.9+ but only required for Python 3.11
    - patches/python3.11.patch  # [py>=311]

    # https://bugreports.qt.io/browse/PYSIDE-1775
    - patches/pymangle.patch

    # https://bugreports.qt.io/browse/PYSIDE-2183
    - patches/support.patch

    # https://bugreports.qt.io/browse/PYSIDE-2184
    - patches/install_pyi.patch

    # https://bugreports.qt.io/browse/PYSIDE-2187
    - patches/gluint.patch

build:
  number: 2
  detect_binary_files_with_prefix: true
  entry_points:
    - pyside2-designer = PySide2.scripts.pyside_tool:designer
    - pyside2-rcc = PySide2.scripts.pyside_tool:rcc
    - pyside2-uic = PySide2.scripts.pyside_tool:uic
  ignore_run_exports:
    # make it optional. Use the constraints on qt-main
    # and qt to ensure that qt-webengine is correctly installed
    - qt-webengine

requirements:
  build:
    - sysroot_linux-64 2.17                  # [linux64]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pyside2  {{ qt_main }}                 # [build_platform != target_platform]
    - qt-main                                # [build_platform != target_platform]
    - qt-webengine                           # [build_platform != target_platform]
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clangdev
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxrandr') }}             # [linux]
    - {{ cdt('alsa-lib') }}              # [linux]
    - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]

  host:
    - python
    - packaging
    - qt-main
    - qt-webengine
    - libxml2
    - libxslt
    - pip
    - setuptools
    - libclang
  run:
    - python

test:
  imports:
    - PySide2.QtCharts
    - PySide2.QtConcurrent
    - PySide2.QtCore
    - PySide2.QtDataVisualization
    - PySide2.QtGui
    - PySide2.QtHelp
    - PySide2.QtLocation
    - PySide2.QtMultimedia
    - PySide2.QtMultimediaWidgets
    - PySide2.QtNetwork
    - PySide2.QtOpenGL
    - PySide2.QtPositioning
    - PySide2.QtPrintSupport
    - PySide2.QtQml
    - PySide2.QtQuick
    - PySide2.QtQuickWidgets
    - PySide2.QtRemoteObjects
    - PySide2.QtScript
    - PySide2.QtScriptTools
    - PySide2.QtScxml
    - PySide2.QtSensors
    - PySide2.QtSql
    - PySide2.QtSvg
    - PySide2.QtTest
    - PySide2.QtTextToSpeech
    - PySide2.QtUiTools
    - PySide2.QtWebChannel
    - PySide2.QtWebEngineCore     # [py==310]
    - PySide2.QtWebEngineWidgets  # [py==310]
    - PySide2.QtWebSockets
    - PySide2.QtWidgets
    - PySide2.QtXml
    - PySide2.QtXmlPatterns
    - PySide2.Qt3DAnimation
    - PySide2.Qt3DCore
    - PySide2.Qt3DExtras
    - PySide2.Qt3DInput
    - PySide2.Qt3DLogic
    - PySide2.Qt3DRender

  commands:
    - shiboken2 --help
    - pyside2-lupdate -help
    - pyside2-rcc -help
    - pyside2-uic -help
    # Ensure installs are registered properly with pip
    - pip show PySide2
    - pip show shiboken2

  requires:
    - pip
    - qt-webengine   # [py==310]

about:
  home: https://wiki.qt.io/PySide2
  license: LGPL-3.0-only
  license_file: LICENSE.LGPLv3
  summary: Python bindings for Qt

extra:
  recipe-maintainers:
    - jan-janssen
    - jschueller
    - hmaarrfk
