{% set version = "5.13.1" %}

package:
  name: pyside2
  version: {{ version }}

source:
  fn: pyside-setup-everywhere-src-{{ version }}.tar.xz
  url: https://download.qt.io/official_releases/QtForPython/pyside2/PySide2-{{ version }}-src/pyside-setup-everywhere-src-{{ version }}.tar.xz
  sha256: c57c71ddece90b29d0934cf5fac1e1634719484637b56dcbe49eb277c1c01536
  patches:
    # https://codereview.qt-project.org/c/pyside/pyside-tools/+/270008
    - 0001-Make-pyside2-uic-executable-by-windows-shell.patch
    # Symbol not found: __cg_jpeg_resync_to_restart
    - no_pyi.patch  # [osx]

build:
  number: 1
  skip: true  # [win and vc<14]
  detect_binary_files_with_prefix: True

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxrandr') }}             # [linux]
    - {{ cdt('alsa-lib') }}              # [linux]
    - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]

  host:
    - clangdev
    - llvmdev
    - python
    - qt
    - libxslt
    - libxml2
  run:
    - clangdev
    - llvmdev
    - python
    - qt
    - libxslt
    - libxml2

test:
  commands:
    - shiboken2 --help

about:
  home: https://wiki.qt.io/PySide2
  license: LGPL3
  license_file: LICENSE.LGPLv3
  summary: Python bindings for Qt

extra:
  recipe-maintainers:
    - jschueller
