{% set version = "6.7.3" %}
{% set version_major_minor_match = '.'.join(version.split('.')[0:3]) %}

package:
  name: pyside6
  version: {{ version }}

source:
  url: https://download.qt.io/official_releases/QtForPython/pyside6/PySide6-{{ version }}-src/pyside-setup-everywhere-src-{{ version }}.tar.xz
  sha256: a4c414be013d5051a2d10a9a1151e686488a3172c08a57461ea04b0a0ab74e09
  patches:
    # https://bugreports.qt.io/browse/PYSIDE-1193
    - patches/pyi_osx.patch
    - patches/qfp_osx.patch

    # https://bugreports.qt.io/browse/PYSIDE-2057
    - patches/do_not_store_build_time_compiler.patch

    # change tools module location
    - patches/tools.patch

build:
  number: 1
  entry_points:
    - pyside6-rcc = PySide6.scripts.pyside_tool:rcc
    - pyside6-uic = PySide6.scripts.pyside_tool:uic
  ignore_run_exports:
    # make it optional
    - qt6-3d
    - qt6-charts
    - qt6-datavis3d
    - qt6-graphs
    - qt6-wayland
    - qt6-multimedia
    - qt6-quick3d

requirements:
  build:
    - cmake
    - ninja
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libclang                           # [build_platform != target_platform]
    - llvmdev                            # [build_platform != target_platform]
    - clangdev                           # [build_platform != target_platform]
    - python                             # [build_platform != target_platform]
    - setuptools                         # [build_platform != target_platform]
    #- cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - libxslt                            # [build_platform != target_platform]
    - libxml2                            # [build_platform != target_platform]
    - qt6-main {{ version }}             # [build_platform != target_platform]

  host:
    - libgl-devel                        # [linux]
    - libegl-devel                       # [linux]
    - libopengl-devel                    # [linux]
    - libvulkan-headers                  # [not osx]
    - libvulkan-loader                   # [not osx]
    - python
    - setuptools
    - libxslt
    - libxml2
    - qt6-main {{ version }}
    - qt6-3d
    - qt6-charts
    - qt6-datavis3d
    - qt6-graphs
    - qt6-wayland  # [linux]
    # Provides QtMultimediaWidgets and QtSpatialAudio
    - qt6-multimedia
    - qt6-quick3d
    - llvmdev
    - clangdev >=9
    - libclang
    - llvmdev  {{ cxx_compiler_version }}  # [osx]
    - clangdev {{ cxx_compiler_version }}  # [osx]
  run:
    - python
    - qt6-main {{ version }}

test:
  requires:
    # these are optional
    # test them with one version of python
    - qt6-3d               # [py==310]
    - qt6-charts           # [py==310]
    - qt6-datavis3d        # [py==310]
    - qt6-graphs           # [py==310]
    - qt6-multimedia       # [py==310]
  imports:
    - PySide6.Qt3DAnimation        # [py==310]
    - PySide6.Qt3DCore             # [py==310]
    - PySide6.Qt3DExtras           # [py==310]
    - PySide6.Qt3DInput            # [py==310]
    - PySide6.Qt3DLogic            # [py==310]
    - PySide6.Qt3DRender           # [py==310]
    #- PySide6.QtBluetooth
    - PySide6.QtCharts             # [py==310]
    - PySide6.QtConcurrent
    - PySide6.QtCore
    - PySide6.QtDataVisualization  # [py==310]
    - PySide6.QtDesigner
    - PySide6.QtGraphs             # [py==310]
    - PySide6.QtGui
    - PySide6.QtHelp
    #- PySide6.QtHttpServer
    - PySide6.QtMultimedia         # [py==310]
    - PySide6.QtMultimediaWidgets  # [py==310]
    - PySide6.QtNetwork
    #- PySide6.QtNetworkAuth
    #- PySide6.QtNfc
    - PySide6.QtOpenGL
    - PySide6.QtOpenGLWidgets
    #- PySide6.QtPdf
    #- PySide6.QtPdfWidgets
    # - PySide6.QtPositioning
    - PySide6.QtPrintSupport
    - PySide6.QtQml
    - PySide6.QtQuick
    - PySide6.QtQuick3D            # [py==310]
    - PySide6.QtQuickControls2
    - PySide6.QtQuickWidgets
    #- PySide6.QtRemoteObjects
    # - PySide6.QtScxml
    # - PySide6.QtSensors
    # - PySide6.QtSerialPort
    - PySide6.QtSpatialAudio       # [py==310]
    - PySide6.QtSql
    #- PySide6.QtStateMachine
    - PySide6.QtSvg
    - PySide6.QtSvgWidgets
    - PySide6.QtTest
    #- PySide6.QtTextToSpeech
    - PySide6.QtUiTools
    - PySide6.QtWebChannel
    #- PySide6.QtWebEngineCore
    #- PySide6.QtWebEngineQuick
    #- PySide6.QtWebEngineWidgets
    - PySide6.QtWebSockets
    - PySide6.QtWidgets
    - PySide6.QtXml
  commands:
    - shiboken6 --help
    - pyside6-rcc -help
    - pyside6-uic -help
    - test -f ${PREFIX}/lib/qt6/plugins/designer/libPySidePlugin${SHLIB_EXT}  # [unix]
    # Regression to avoid clobber with qt-main package
    - test ! -f $PREFIX/bin/uic  # [unix]
    - if exist %LIBRARY_BIN%\uic.exe exit 1  # [win]

about:
  home: https://wiki.qt.io/PySide2
  license: LGPL-3.0-only
  license_file: LICENSES/LGPL-3.0-only.txt
  summary: Python bindings for Qt

extra:
  recipe-maintainers:
    - jan-janssen
    - jschueller
