{% set version = "5.6.0a1" %}

package:
  name: pyside2
  version: {{ version }}

source:
  git_url: https://codereview.qt-project.org/pyside/pyside-setup
  git_tag: 5.6

build:
  number: 1003
  detect_binary_files_with_prefix: True

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - qt
    - libxslt
    - libxml2
    - libxcb   # [linux]
    - mesalib  # [linux]
  run:
    - python
    - qt
    - libxslt
    - libxml2
    - libxcb   # [linux]
    - mesalib  # [linux]

test:
  imports:
    - PySide2.QtConcurrent
    - PySide2.QtCore
    - PySide2.QtGui
    - PySide2.QtHelp
    - PySide2.QtMultimedia
    - PySide2.QtMultimediaWidgets
    - PySide2.QtNetwork
    - PySide2.QtOpenGL
    - PySide2.QtPrintSupport
    - PySide2.QtQml
    - PySide2.QtQuick
    - PySide2.QtQuickWidgets
    - PySide2.QtScript
    - PySide2.QtScriptTools
    - PySide2.QtSql
    - PySide2.QtSvg
    - PySide2.QtTest
    - PySide2.QtUiTools
    - PySide2.QtWebChannel
    - PySide2.QtWebSockets
    - PySide2.QtWidgets
    - PySide2.QtXml
    - PySide2.QtXmlPatterns
  commands:
    - shiboken2 --help
    - pyside2-lupdate -help
    - pyside2-rcc -help
    - pyside2-uic -help

about:
  home: https://wiki.qt.io/PySide2
  license: LGPL3
  license_file: LICENSE.LGPL3
  summary: Python bindings for Qt

extra:
  recipe-maintainers:
    - jschueller
