{% set version = "6.5.1" %}

package:
  name: pyside6
  version: {{ version }}

source:
  url: https://download.qt.io/official_releases/QtForPython/pyside6/PySide6-{{ version }}-src/pyside-setup-everywhere-src-{{ version }}.tar.xz
  sha256: bc9153cbcc0cd234f3955c5eb90fe1191060b026adc7ea348fd6a6a9868bb8fe
  patches:
    # https://bugreports.qt.io/browse/PYSIDE-1193
    - patches/pyi_osx.patch

    # https://bugreports.qt.io/browse/PYSIDE-2057
    - patches/do_not_store_build_time_compiler.patch

    # https://bugreports.qt.io/browse/PYSIDE-2090
    - patches/build_generator.patch

    # https://bugreports.qt.io/browse/PYSIDE-2184
    - patches/install_pyi.patch

    # change tools module location
    - patches/tools.patch

    # https://bugreports.qt.io/browse/PYSIDE-2294
    # https://codereview.qt-project.org/c/pyside/pyside-setup/+/471544
    # https://github.com/napari/napari/issues/5703
    - patches/fix_2294_e99951f.patch

build:
  number: 1
  entry_points:
    - pyside6-rcc = PySide6.scripts.pyside_tool:rcc
    - pyside6-uic = PySide6.scripts.pyside_tool:uic
  ignore_run_exports:
    # make it optional
    - qt6-3d
    - qt6-charts
    - qt6-datavis3d

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libclang                           # [build_platform != target_platform]
    - llvmdev                            # [build_platform != target_platform]
    - clangdev >=9                       # [build_platform != target_platform]
    - python                             # [build_platform != target_platform]
    #- cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - libxslt                            # [build_platform != target_platform]
    - libxml2                            # [build_platform != target_platform]
    - qt6-main                           # [build_platform != target_platform]
    - sysroot_linux-64 2.17              # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libglvnd-glx') }}          # [linux]
    - {{ cdt('libglvnd-egl') }}          # [linux]

  host:
    - python
    - libxslt
    - libxml2
    - qt6-main {{ version }}
    - qt6-3d
    - qt6-charts
    - qt6-datavis3d
    - llvmdev
    - clangdev >=9
    - libclang
    - llvmdev  {{ cxx_compiler_version }}  # [osx]
    - clangdev {{ cxx_compiler_version }}  # [osx]
  run:
    - python
    - {{ pin_compatible("libclang") }}

test:
  requires:
    # these are optional
    # test them with one version of python
    - qt6-3d               # [py==310]
    - qt6-charts           # [py==310]
    - qt6-datavis3d        # [py==310]

    - sysroot_linux-64 2.17              # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libglvnd-glx') }}          # [linux]
    - {{ cdt('libglvnd-egl') }}          # [linux]
  imports:
    - PySide6.Qt3DAnimation        # [py==310]
    - PySide6.Qt3DCore             # [py==310]
    - PySide6.Qt3DExtras           # [py==310]
    - PySide6.Qt3DInput            # [py==310]
    - PySide6.Qt3DLogic            # [py==310]
    - PySide6.Qt3DRender           # [py==310]
    #- PySide6.QtBluetooth
    - PySide6.QtCharts             # [py==310]
    - PySide6.QtConcurrent
    - PySide6.QtCore
    - PySide6.QtDataVisualization  # [py==310]
    - PySide6.QtDesigner
    - PySide6.QtGui
    - PySide6.QtHelp
    #- PySide6.QtHttpServer
    - PySide6.QtMultimedia
    - PySide6.QtMultimediaWidgets
    - PySide6.QtNetwork
    #- PySide6.QtNetworkAuth
    #- PySide6.QtNfc
    - PySide6.QtOpenGL
    - PySide6.QtOpenGLWidgets
    #- PySide6.QtPdf
    #- PySide6.QtPdfWidgets
    # - PySide6.QtPositioning
    - PySide6.QtPrintSupport
    - PySide6.QtQml
    - PySide6.QtQuick
    #- PySide6.QtQuick3D
    - PySide6.QtQuickControls2
    - PySide6.QtQuickWidgets
    #- PySide6.QtRemoteObjects
    # - PySide6.QtScxml
    # - PySide6.QtSensors
    # - PySide6.QtSerialPort
    - PySide6.QtSpatialAudio
    - PySide6.QtSql
    #- PySide6.QtStateMachine
    - PySide6.QtSvg
    - PySide6.QtSvgWidgets
    - PySide6.QtTest
    #- PySide6.QtTextToSpeech
    - PySide6.QtUiTools
    - PySide6.QtWebChannel
    #- PySide6.QtWebEngineCore
    #- PySide6.QtWebEngineQuick
    #- PySide6.QtWebEngineWidgets
    - PySide6.QtWebSockets
    - PySide6.QtWidgets
    - PySide6.QtXml
  commands:
    - shiboken6 --help
    - pyside6-rcc -help
    - pyside6-uic -help

about:
  home: https://wiki.qt.io/PySide2
  license: LGPL-3.0-only
  license_file: LICENSES/LGPL-3.0-only.txt
  summary: Python bindings for Qt

extra:
  recipe-maintainers:
    - jan-janssen
    - jschueller
