build_platform:
  linux_aarch64: linux_aarch64
os_version:
  linux_64: cos7
provider:
  linux_aarch64: azure
  win: azure
github:
  branch_name: main
  tooling_branch_name: main
test_on_native_only: true
conda_forge_output_validation: true
