build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_aarch64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: azure
test: native_and_emulated
