build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
provider:
  linux_aarch64: azure
test: native_and_emulated
