appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: NYF5FvAPggLEHNAx8aXlx7lCztX4CK5EM5p4CRw1YC2e2teW1gLbSO0vktS32o4vu5DY/tjhYgJcDbqGkefgZdAVNrdtc8cdHM12zWp555JaAhB+2kav/9RV9QbGkIVeR2d9yxFhA9WpACN3Msni6EJMMbABwLa5HDYBsxMw6vLHBPq8UpDpfkN5ZUs+fwM+f1yu5fakLj3uV6QuwbH60a1y6Vr5Ii4+Al0VPao7wVQgEgwIYMh/TKnIpB4P7TKBHBmn2AmxSffiCNR1tHxEClVR1V8wF7VS86qrxD7tzRFzMVFxUx+RonykAwTQ6dWPQU8p1zycqg8h/22HujKqNTECx2hmtrCt2gl2ZtCH/qGltqeuyQrtEkEhoPnySTbOmnhN/q4VPcwmj7YzRaLxjleYKiIh9jXslGbxnK4EwGqL2fIl+IJE5qFjnQHC4ZJk9aPrOwvmC8WlfoE2nZ9V4c6e1B6zVtFsfPwGo3QoFHNQFrxUKyilKG8Y95/YkMa7TWJR1QBBl5Rw/CPM7bgNvm9KK3zUvPjjjysKm7ACp0DIEp4E5vodXSMHp4WH1uEZNfwXC7LV21MjZ796WSWf0q+WaLcYJO0g64lifZrlYx33AVVr7imqh60mTHIALzGyq+4yIPAMv1z2sU+H70ThfvhJ5QDfXTO4EpkvAiToidw=}

provider:
  win: azure
